Python1807AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^jingluo/', include('app.urls', namespace='axf')),
]

app/urls.py
from django.conf.urls import url
from app import views

urlpatterns = [
    url(r'^$', views.home, name='home'),            # 首页

    url(r'^home/$', views.home, name='home'),       # 首页
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.market, name='market'), # 闪购超市
    url(r'^cart/$', views.cart, name='cart'),       # 购物车

    url(r'^mine/$', views.mine, name='mine'),       # 我的
    url(r'^register/$', views.register, name='register'), # 注册
    url(r'^login/$', views.login, name='login'),    # 登录
    url(r'^logout/$', views.quit, name='logout'),   # 退出登录
    url(r'checkuser/$', views.checkuser, name='checkuser'), # 用户名验证

    url(r'^addtocart/$', views.addtocart, name='addtocart'),    # 添加到购物车
    url(r'^subtocart/$', views.subtocart, name='subtocart'),    # 购物车删减
    url(r'changecartstatus/$', views.changecartstatus, name='changecartstatus'), # 修改选中状态
    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),   # 全选/取消全选

    url(r'^generateorder/$', views.generateorder, name='generateorder'),    # 下单
    url(r'^orderinfo/$', views.orderinfo, name='orderinfo'),    # 订单详情
    url(r'^changeorderstatus/$', views.changeorderstatusm, name='changeorderstatus'),   # 修改订单状态
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    {#   标题#}
    {% block title %}
    {% endblock %}

    {#   样式表#}
    {% block EXTCSS %}
    {% endblock %}
</head>
<body>

{# 头部#}
{% block header %}
    <header>巨鲸落</header>
{% endblock %}


{# 主体内容#}
<div class="hidescroll">
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</div>

{# 尾部#}
{% block footer %}
    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt><span></span></dt>
                <dd> 首页</dd>
            </dl>
        </a>
        <a href="{% url 'axf:market' 104749 0 0 %}" class="market">
            <dl>
                <dt><span></span></dt>
                <dd> 易购超市 </dd>
            </dl>
        </a>
        <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt><span></span></dt>
                <dd> 购物车</dd>
            </dl>
        </a>
        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt><span></span></dt>
                <dd> 我的 </dd>
            </dl>
        </a>
    </footer>
{% endblock %}


<script src="{% static 'base/js/jquery.js' %}"></script>
<script src="{% static 'base/js/jquery.cookie.js' %}"></script>
<script src="{% static 'base/js/bootstrap.js' %}"></script>
<script src="{% static 'base/js/swiper.js' %}"></script>
<script src="{% static 'base/js/base.js' %}"></script>
{# JS#}
{% block EXTJS %}
{% endblock %}
</body>
</html>