Python1807AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^jingluo/', include('app.urls', namespace='axf')),
]

app/urls.py
from django.conf.urls import url
from app import views

urlpatterns = [
    url(r'^$', views.home, name='home'),            # 首页

    url(r'^home/$', views.home, name='home'),       # 首页
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.market, name='market'), # 闪购超市
    url(r'^cart/$', views.cart, name='cart'),       # 购物车

    url(r'^mine/$', views.mine, name='mine'),       # 我的
    url(r'^register/$', views.register, name='register'), # 注册
    url(r'^login/$', views.login, name='login'),    # 登录
    url(r'^logout/$', views.quit, name='logout'),   # 退出登录
    url(r'checkuser/$', views.checkuser, name='checkuser'), # 用户名验证

    url(r'^addtocart/$', views.addtocart, name='addtocart'),    # 添加到购物车
    url(r'^subtocart/$', views.subtocart, name='subtocart'),    # 购物车删减
    url(r'changecartstatus/$', views.changecartstatus, name='changecartstatus'), # 修改选中状态
    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),   # 全选/取消全选

    url(r'^generateorder/$', views.generateorder, name='generateorder'),    # 下单
    url(r'^orderinfo/$', views.orderinfo, name='orderinfo'),    # 订单详情
    url(r'^changeorderstatus/$', views.changeorderstatusm, name='changeorderstatus'),   # 修改订单状态
]

templates/mine/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block EXTCSS %}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}

{% block title %}
    <title>登录界面</title>
{% endblock %}

{% block content %}
<div class="login">
    <div class="back"><a href="{% url 'axf:mine' %}"> <span class=" glyphicon glyphicon-remove "></span> </a> </div>

    <form action="{% url 'axf:login' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">账号</span>
            <input type="text" class="form-control" placeholder="6~12位数" aria-describedby="basic-addon1" name="account">
        </div>

        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">密码</span>
            <input type="password" class="form-control" placeholder="6~12位数" aria-describedby="basic-addon1" name="password">
        </div>

        {% if error %}
            <p class="err">{{ error }}</p>
        {% endif %}

        <input class="btn btn-primary" value="登录" id="subButton" type="submit">
    </form>
</div>
{% endblock %}


{% block EXTJS %}
    <script src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}

templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}

{% block EXTCSS %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}

{% block title %}
<title>我的</title>
{% endblock %}


{% block content %}
<div class="mine">
    <div class="user-wrapper">
        <div class="user-img">
            <img src="{{ img }}" alt="">
        </div>
        <div class="user-content">
            <p> <a href="{% url 'axf:login' %}"> <span class="glyphicon glyphicon-user"></span> {{ name }} </a> </p>
            <p> <span class="glyphicon glyphicon-king"></span> VIP: {{ rank }} </p>
            <a href="{% url 'axf:register' %}" class="register"> 注册 </a>
        </div>

    </div>

    <div class="collect">
        <b class="glyphicon glyphicon-link"></b>
        <span>收藏</span>
    </div>

    <div class="other">
        <section class="my">
            <span>我的订单</span>
            <a href="#"> 查看全部订单 <i class="glyphicon glyphicon-chevron-right"></i> </a>
        </section>

        <section>
            <ul>
                <li>
                    <a href="#">
                        <dl class="item">
                            <dt>
                                <span class="glyphicon glyphicon-gift"></span>
                                {% if wait_pay %}
                                    <i class="badge">{{ wait_pay }}</i>
                                {% endif %}
                            </dt>
                            <dd> 待付款 </dd>
                        </dl>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <dl class="item">
                            <dt>
                                <span class="glyphicon glyphicon-hourglass"></span>
                                {% if payed %}
                                    <i class="badge">{{ payed }}</i>
                                {% endif %}
                            </dt>
                            <dd> 待收货 </dd>
                        </dl>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <dl>
                            <dt> <span class="glyphicon glyphicon-edit"></span> </dt>
                            <dd> 待评价 </dd>
                        </dl>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <dl>
                            <dt> <span class="glyphicon glyphicon-refresh"></span> </dt>
                            <dd> 退款/售后 </dd>
                        </dl>
                    </a>
                </li>
            </ul>
        </section>

        <section>
            <ul>
                <li>
                    <a href="#">
                        <dl>
                            <dt><span class="glyphicon glyphicon-yen"></span></dt>
                            <dd> 优惠券 </dd>
                        </dl>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <dl>
                            <dt> <span class="glyphicon glyphicon-globe"></span> </dt>
                            <dd> 收货地址 </dd>
                        </dl>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <dl>
                            <dt> <span class="glyphicon glyphicon-send"></span> </dt>
                            <dd> 客户反馈 </dd>
                        </dl>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <dl>
                            <dt> <span class="glyphicon glyphicon-phone-alt"></span> </dt>
                            <dd> 联系我们 </dd>
                        </dl>
                    </a>
                </li>
            </ul>
        </section>

        {% if islogin %}
            <section class="quit">
                <a href="{% url 'axf:logout' %}">退出</a>
            </section>
        {% endif %}
    </div>
</div>
{% endblock %}


{% block EXTJS %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

templates/mine/register.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    <title>注册界面</title>
{% endblock %}

{% block EXTCSS %}
    <link rel="stylesheet" href="{% static '/mine/css/register.css' %}">
{% endblock %}


{% block content %}
<div class="register">
    <div class="back"><a href="{% url 'axf:mine' %}"> <span class=" glyphicon glyphicon-remove "></span> </a> </div>

    <form action="{% url 'axf:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">账号</span>
            <input id="account" type="text" class="form-control" placeholder="账号" aria-describedby="basic-addon1" name="account">
        </div>
        <span class="error" id="accounterr"></span>

        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">密码</span>
            <input type="password" class="form-control" placeholder="6~12位数" aria-describedby="basic-addon1" name="password" id="password">
        </div>
        <span class="error" id="passworderr">密码格式不正确</span>

        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">验证</span>
            <input type="password" class="form-control" placeholder="6~12位数" aria-describedby="basic-addon1" name="mypassword" id="mypassword">
        </div>
        <span class="error" id="mypassworderr">密码输入不一致</span>

        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">大名</span>
            <input type="text" class="form-control" placeholder="大名" aria-describedby="basic-addon1" name="name">
        </div>

{#        .has-success#}
        <div class="input-group tel-view" >
            <span class="input-group-addon" id="basic-addon1">电话</span>
            <input type="text" class="form-control" placeholder="电话" aria-describedby="basic-addon1" name="tel" id="tel">
             <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
        </div>

        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">地址</span>
            <input type="text" class="form-control" placeholder="地址" aria-describedby="basic-addon1" name="address">
        </div>

        <div class="form-group">
            <input type="file" name="file"/>
        </div>

        <input class="btn btn-primary" value="注册" id="subButton" type="submit">
    </form>
</div>
{% endblock %}



{% block EXTJS %}
    <script src="{% static 'mine/js/registe.js' %}"></script>
{% endblock %}